<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AsistenciaTratamiento;

/**
 * AsistenciaTratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsistenciaTratamientoRepository extends \Doctrine\ORM\EntityRepository
{
    public function ultimaAsistenciaTratamientoEsquema($idEsquema)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT a FROM AppBundle:AsistenciaTratamiento a 
                JOIN a.esquemaMedicamentos em 
                WHERE em.id = :idEsquema
                ORDER BY a.fecha DESC";
        $query = $em->createQuery($dql);
        $query->setParameter('idEsquema' , $idEsquema);
        $asistencia = $query->setMaxResults(1)->getResult();

        if(count($asistencia) != 0 ) return $asistencia[0];
        else return null;
    }

    public function asistenciasTratamientosMesEsquema($mes , $anno , $idEsquema)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT a FROM AppBundle:AsistenciaTratamiento a 
                JOIN a.esquemaMedicamentos em 
                WHERE em.id = :idEsquema
                AND a.fecha LIKE :fecha
                ORDER BY a.fecha ASC";

        $query = $em->createQuery($dql);
        $query->setParameter('idEsquema' , $idEsquema);
        $query->setParameter('fecha' , $anno.'-'.$mes.'%');
        $asistencias = $query->getResult();

        return $asistencias;

    }

    public function actualizarAsistenciasMes($idEsquema , $fechasMarcadas , $fecha)
    {
        try
        {
            $em = $this->getEntityManager();
            $esquema = $em->getRepository('AppBundle:EsquemaMedicamentos')->find($idEsquema);

            $arreglo = explode('-', $fecha);
            $asitenciasOld = $this->asistenciasTratamientosMesEsquema($arreglo[1] , $arreglo[0] , $idEsquema);

            foreach ($asitenciasOld as $asistencia)
            {
                $em->remove($asistencia);
            }

            if(!empty($fechasMarcadas))
            {
                foreach ($fechasMarcadas as $fecha)
                {
                    $asistenciaNew = new AsistenciaTratamiento();
                    $asistenciaNew->setEsquemaMedicamentos($esquema);
                    $asistenciaNew->setFecha(new \DateTime($fecha));
                    $em->persist($asistenciaNew);
                }
            }
            $em->flush();
            $msg = count($esquema->getAsistenciasTratamientos());

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al guerdar los datos';
        }

        return $msg;
    }
}
