<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Baciloscopia;

/**
 * BaciloscopiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaciloscopiaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarBaciloscopia($data)
    {
        try{
            $em = $this->getEntityManager();
            $baciloscopia = new Baciloscopia();
            $baciloscopia->setClasificacion($data['clasificacion']);
            $baciloscopia->setDescripcion($data['descripcion']);

            $em->persist($baciloscopia);
            $em->flush();
            $msg = $baciloscopia;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La Baciloscopía ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la Baciloscopía';
            }
        }

        return $msg;
    }

    public function modificarBaciloscopia($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->find($data['idBaciloscopia']);
            $baciloscopia->setDescripcion($data['descripcion']);

            $em->persist($baciloscopia);
            $em->flush();
            $msg = $baciloscopia;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la Baciloscopía';
        }

        return $msg;
    }

    public function eliminarBaciloscopia($id)
    {
        try {
            $em = $this->getEntityManager();
            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->find($id);

            $em->remove($baciloscopia);
            $em->flush();
            $msg = $baciloscopia;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes con resultados asociados a esta Baciloscopia , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la Baciloscopia';
            }
        }
        return $msg;
    }
}
