<?php

namespace AppBundle\Repository;

/**
 * BiopsiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiopsiaRepository extends \Doctrine\ORM\EntityRepository
{
}
