<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CausaNoPrescripcionTPT;

/**
 * CausaNoPrescripcionTPTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CausaNoPrescripcionTPTRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarCausaNoPrescripcion($data)
    {
        try{
            $em = $this->getEntityManager();
            $causaNoPrescripcion = new CausaNoPrescripcionTPT();
            $causaNoPrescripcion->setNombre($data['nombre']);

            $em->persist($causaNoPrescripcion);
            $em->flush();
            $msg = $causaNoPrescripcion;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La causa de no prescripción TPT ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la causa de no prescripción TPT';
            }
        }

        return $msg;
    }

    public function modificarCausaNoPrescripcion($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $causaNoPrescripcion = $em->getRepository('AppBundle:CausaNoPrescripcionTPT')->find($data['idCausaNoPrescripcion']);
            $causaNoPrescripcion->setNombre($data['nombre']);

            $em->persist($causaNoPrescripcion);
            $em->flush();
            $msg = $causaNoPrescripcion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la causa de no prescripción TPT';
        }

        return $msg;
    }

    public function eliminarCausaNoPrescripcion($id)
    {
        try {
            $em = $this->getEntityManager();
            $causaNoPrescripcion = $em->getRepository('AppBundle:CausaNoPrescripcionTPT')->find($id);

            $em->remove($causaNoPrescripcion);
            $em->flush();
            $msg = $causaNoPrescripcion;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen contactos con esta causa de no prescripción TPT, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la causa de no prescripción TPT';
            }
        }
        return $msg;
    }

}
