<?php

namespace AppBundle\Repository;
use AppBundle\Entity\DireccionPaciente;

/**
 * DireccionPacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionPacienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarDireccion($data)
    {
        try{
            $em = $this->getEntityManager();
            $direccion = new DireccionPaciente();
            $direccion->setDireccion($data['direccion']);

            $municipio = $em->getRepository('AppBundle:Municipio')->find($data['municipio']);
            $direccion->setMunicipio($municipio);

            $em->persist($direccion);
            $em->flush();
            $msg = $direccion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar la dirección del paciente';
        }
        return $msg;
    }

    public function modificarDireccion($data)
    {
        try{
            $em = $this->getEntityManager();
            $direccion = $em->getRepository('AppBundle:DireccionPaciente')->find($data['idDireccion']);
            $direccion->setDireccion($data['direccion']);

            $municipio = $em->getRepository('AppBundle:Municipio')->find($data['municipio']);
            $direccion->setMunicipio($municipio);

            $em->persist($direccion);
            $em->flush();
            $msg = $direccion;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la dirección del paciente';
        }
        return $msg;
    }
}
