<?php

namespace AppBundle\Repository;

use AppBundle\Entity\EstadoGrafico;

/**
 * EstadoGraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoGraficoRepository extends \Doctrine\ORM\EntityRepository
{

    public function agregarEstadoGrafico($data)
    {
        try{
            $em = $this->getEntityManager();
            $estadoGrafico = new EstadoGrafico();
            $estadoGrafico->setYear($data['year']);
            $estadoGrafico->setValorInicial($data['valorInicial']);
            $estadoGrafico->setValorFinal($data['valorFinal']);

            $em->persist($estadoGrafico);
            $em->flush();
            $msg = $estadoGrafico;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'Este año ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al modificar el estado del gráfico';
            }
        }
        return $msg;
    }

    public function modificarEstadoGrafico($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $estadoGrafico = $em->getRepository('AppBundle:EstadoGrafico')->find($data['idEstadoGrafico']);
            $estadoGrafico->setYear($data['year']);
            $estadoGrafico->setValorInicial($data['valorInicial']);
            $estadoGrafico->setValorFinal($data['valorFinal']);

            $em->persist($estadoGrafico);
            $em->flush();
            $msg = $estadoGrafico;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'Este año ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al modificar el estado del gráfico';
            }
        }

        return $msg;
    }

    public function eliminarEstadoGrafico($id)
    {
        try {
            $em = $this->getEntityManager();
            $estadoGrafico = $em->getRepository('AppBundle:EstadoGrafico')->find($id);

            $em->remove($estadoGrafico);
            $em->flush();
            $msg = $estadoGrafico;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen estado de gráficos asociados a este año, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error el estado de gráfico.';
            }
        }
        return $msg;
    }

}
