<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Laboratorio;

/**
 * LaboratorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratorioRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarLaboratorio($data)
    {
        $msg = 'ok';
        try{
            $em = $this->getEntityManager();
            $lab = new Laboratorio();
            $lab->setNombre($data['nombre']);

            $municipio  = $em->getRepository('AppBundle:Municipio')->find($data['id_municipio']);
            $lab->setMunicipio($municipio);

            $em->persist($lab);
            $em->flush();

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El Laboratorio ya existe , no se puede agregar.';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el Laboratorio.';
            }
        }

        return $msg;
    }

    public function modificarLaboratorio($data)
    {
        $msg = 'ok';

        try
        {
            $em = $this->getEntityManager();
            $lab = $em->getRepository('AppBundle:Laboratorio')->find($data['id_laboratorio']);
            $lab->setNombre($data['nombre']);

            $municipio  = $em->getRepository('AppBundle:Municipio')->find($data['id_municipio']);
            $lab->setMunicipio($municipio);

            $em->persist($lab);
            $em->flush();

        }catch (\Exception $e)
        {
            $msg = 'Error';
        }

        return $msg;
    }

    public function eliminarLaboratorio($id)
    {
        try {
            $em = $this->getEntityManager();
            $lab = $em->getRepository('AppBundle:Laboratorio')->find($id);

            $em->remove($lab);
            $em->flush();
            $msg = $lab;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen tablas asociadas a este Laboratorio , no se puede eliminar.';
            } else {
                $msg = 'Se produjo un error al eliminar el Laboratorio.';
            }
        }
        return $msg;
    }
}
