<?php

namespace AppBundle\Repository;
use AppBundle\Entity\MedicamentoPrimeraLinea;

/**
 * MedicamentoPrimeraLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoPrimeraLineaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarMedicamento($data)
    {
        try{
            $em = $this->getEntityManager();
            $medicamento = new MedicamentoPrimeraLinea();
            $medicamento->setNombre($data['nombre']);
            $medicamento->setModulo($data['modulo']);

            $em->persist($medicamento);
            $em->flush();
            $msg = $medicamento;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El Medicamento ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el Medicamento';
            }
        }

        return $msg;
    }

    public function modificarMedicamento($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $medicamento = $em->getRepository('AppBundle:MedicamentoPrimeraLinea')->find($data['idMedicamento']);
            $medicamento->setNombre($data['nombre']);
            $medicamento->setModulo($data['modulo']);

            $em->persist($medicamento);
            $em->flush();
            $msg = $medicamento;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el Medicamento';
        }

        return $msg;
    }

    public function eliminarMedicamento($id)
    {
        try {
            $em = $this->getEntityManager();
            $medicamento = $em->getRepository('AppBundle:MedicamentoPrimeraLinea')->find($id);

            $em->remove($medicamento);
            $em->flush();
            $msg = $medicamento;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes con este Medicamento en su tratamiento , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el Medicamento';
            }
        }
        return $msg;
    }
}
