<?php

namespace AppBundle\Repository;

/**
 * MotivoCierreContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoCierreContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
