<?php

namespace AppBundle\Repository;

/**
 * OrinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrinaRepository extends \Doctrine\ORM\EntityRepository
{
}
