<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Pais;

/**
 * PaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisRepository extends \Doctrine\ORM\EntityRepository
{
    public function  agregarPais($data)
    {
        try{
            $em = $this->getEntityManager();
            $pais = new Pais();
            $pais->setNombre($data['nombre']);
            $pais->setCodigo($data['codigo']);

            $em->persist($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El País ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el País';
            }
        }

        return $msg;
    }

    public function modificarPais($data)
    {
        $msg = 'ok';

        try
        {
            $em = $this->getEntityManager();
            $pais = $em->getRepository('AppBundle:Pais')->find($data['idPais']);
            $pais->setNombre($data['nombre']);

            $em->persist($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el País';
        }

        return $msg;
    }

    public function eliminarPais($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $pais = $em->getRepository('AppBundle:Pais')->find($id);

            $em->remove($pais);
            $em->flush();
            $msg = $pais;

        }catch (\Exception $e){

            if(strpos($e->getMessage() , 'foreign key') > 0)
            {
                $msg = 'Existen datos asociados a este País , no se puede eliminar';
            }
            else
            {
                $msg = 'Se produjo un error al eliminar el País';
            }
        }
        return $msg;
    }
}
