<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Parentesco;

/**
 * ParentescoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentescoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarParentesco($data)
    {
        try{
            $em = $this->getEntityManager();
            $parentesco = new Parentesco();
            $parentesco->setNombre($data['nombre']);

            $em->persist($parentesco);
            $em->flush();
            $msg = $parentesco;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El parentesco ya existe, no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el parentesco';
            }
        }

        return $msg;
    }

    public function modificarParentesco($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $parentesco = $em->getRepository('AppBundle:Parentesco')->find($data['idParentesco']);
            $parentesco->setNombre($data['nombre']);

            $em->persist($parentesco);
            $em->flush();
            $msg = $parentesco;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el parentesco';
        }

        return $msg;
    }

    public function eliminarParentesco($id)
    {
        try {
            $em = $this->getEntityManager();
            $parentesco = $em->getRepository('AppBundle:Parentesco')->find($id);

            $em->remove($parentesco);
            $em->flush();
            $msg = $parentesco;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen contactos con este parentesco, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el parentesco';
            }
        }
        return $msg;
    }

}
