<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Resistencia;

/**
 * ResistenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResistenciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarResistencia($data)
    {
        try{
            $em = $this->getEntityManager();
            $resistencia = new Resistencia();
            $resistencia->setClasificacion($data['clasificacion']);
            $resistencia->setDescripcion($data['descripcion']);

            $em->persist($resistencia);
            $em->flush();
            $msg = $resistencia;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La Resistencia ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar la Resistencia';
            }
        }

        return $msg;
    }

    public function modificarResistencia($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $resistencia = $em->getRepository('AppBundle:Resistencia')->find($data['idResistencia']);
            $resistencia->setDescripcion($data['descripcion']);

            $em->persist($resistencia);
            $em->flush();
            $msg = $resistencia;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar la Resistencia';
        }

        return $msg;
    }

    public function eliminarResistencia($id)
    {
        try {
            $em = $this->getEntityManager();
            $resistencia = $em->getRepository('AppBundle:Resistencia')->find($id);

            $em->remove($resistencia);
            $em->flush();
            $msg = $resistencia;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {

                $msg = 'Existen pacientes con resultados asociados a esta Resistencia , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar la Resistencia';
            }
        }
        return $msg;
    }
}
