<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ResultadoBCFin;

/**
 * ResultadoBCFinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoBCFinRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarResultadoBCFin($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBCFin = new ResultadoBCFin();
            $fecha = new \DateTime('now');
            $resultadoBCFin->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBCFin->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBCFin->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBCFin->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBCFin);
            $em->flush();
            $msg = $resultadoBCFin;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar el resultado  de los análisis correspondientes al final del tratamiento';
        }
        return $msg;
    }

    public function modificarResultadoBCFin($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBCFin = $em->getRepository('AppBundle:ResultadoBCFin')->find($data['idResultadoBCFin']);
            $fecha = new \DateTime('now');
            $resultadoBCFin->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBCFin->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBCFin->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBCFin->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBCFin);
            $em->flush();
            $msg = $resultadoBCFin;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el resultado  de los análisis correspondientes al final del tratamiento';
        }
        return $msg;
    }
}
