<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ResultadoBC5;

/**
 * ResultadoBC5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoBC5Repository extends \Doctrine\ORM\EntityRepository
{
    public function agregarResultadoBC5($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBC5 = new ResultadoBC5();
            $fecha = new \DateTime('now');
            $resultadoBC5->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBC5->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBC5->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBC5->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBC5);
            $em->flush();
            $msg = $resultadoBC5;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar el resultado  de los análisis correspondientes al quinto mes de tratamiento';
        }
        return $msg;
    }

    public function modificarResultadoBC5($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBC5 = $em->getRepository('AppBundle:ResultadoBC5')->find($data['idResultadoBC5']);
            $fecha = new \DateTime('now');
            $resultadoBC5->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBC5->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBC5->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBC5->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBC5);
            $em->flush();
            $msg = $resultadoBC5;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el resultado  de los análisis correspondientes al quinto mes de tratamiento';
        }
        return $msg;
    }
}
