<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ResultadoTratamiento;

/**
 * ResultadoTratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoTratamientoRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarResultadoTratamiento($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoTratamiento = new ResultadoTratamiento();
            $resultadoTratamiento->setResultado($data['resultado']);
            $resultadoTratamiento->setModulo($data['modulo']);

            $em->persist($resultadoTratamiento);
            $em->flush();
            $msg = $resultadoTratamiento;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El Resultado ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el Resultado';
            }
        }

        return $msg;
    }

    public function modificarResultadoTratamiento($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $resultadoTratamiento = $em->getRepository('AppBundle:ResultadoTratamiento')->find($data['idResultadoTratamiento']);
            $resultadoTratamiento->setResultado($data['resultado']);
            $resultadoTratamiento->setModulo($data['modulo']);

            $em->persist($resultadoTratamiento);
            $em->flush();
            $msg = $resultadoTratamiento;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el Resultado';
        }

        return $msg;
    }

    public function eliminarResultadoTratamiento($id)
    {
        try {
            $em = $this->getEntityManager();
            $resultadoTratamiento = $em->getRepository('AppBundle:ResultadoTratamiento')->find($id);

            $em->remove($resultadoTratamiento);
            $em->flush();
            $msg = $resultadoTratamiento;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes asociados de este resultado , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el resultado';
            }
        }
        return $msg;
    }
}
