<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ResultadoBC2;

/**
 * ResultadoBC2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoBC2Repository extends \Doctrine\ORM\EntityRepository
{
    public function agregarResultadoBC2($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBC2 = new ResultadoBC2();
            $fecha = new \DateTime('now');
            $resultadoBC2->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBC2->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBC2->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBC2->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBC2);
            $em->flush();
            $msg = $resultadoBC2;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al insertar el resultado  de los análisis correspondientes al segundo mes de tratamiento';
        }
        return $msg;
    }

    public function modificarResultadoBC2($data)
    {
        try{
            $em = $this->getEntityManager();
            $resultadoBC2 = $em->getRepository('AppBundle:ResultadoBC2')->find($data['idResultadoBC2']);
            $fecha = new \DateTime('now');
            $resultadoBC2->setFecha($fecha);

            $baciloscopia = $em->getRepository('AppBundle:Baciloscopia')->findOneBy(array('clasificacion' => $data['baciloscopia']));
            $resultadoBC2->setBaciloscopia($baciloscopia);

            $cultivo = $em->getRepository('AppBundle:Cultivo')->findOneBy(array('clasificacion' => $data['cultivo']));
            $resultadoBC2->setCultivo($cultivo);

            $salidaCultivo = $em->getRepository('AppBundle:SalidaCultivo')->findOneBy(array('salida' => $data['salidaCultivo']));
            $resultadoBC2->setSalidaCultivo($salidaCultivo);

            $em->persist($resultadoBC2);
            $em->flush();
            $msg = $resultadoBC2;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el resultado  de los análisis correspondientes al segundo mes de tratamiento';
        }
        return $msg;
    }
}
