<?php

namespace AppBundle\Repository;

/**
 * SalidaCultivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidaCultivoRepository extends \Doctrine\ORM\EntityRepository
{
}
