<?php

namespace AppBundle\Repository;
use AppBundle\Entity\SemanaEstadistica;

/**
 * SemanaEstadisticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemanaEstadisticaRepository extends \Doctrine\ORM\EntityRepository
{
    public function  agregarSemanaEstadistica($data)
    {
        try{
            $em = $this->getEntityManager();
            $semanaEstadistica = new SemanaEstadistica();
            $semanaEstadistica->setSemana($data['semana']);
            $semanaEstadistica->setFechaInicio(new \DateTime($data['fechaInicio']));
            $semanaEstadistica->setFechaFinal(new \DateTime($data['fechaFinal']));

            $em->persist($semanaEstadistica);
            $em->flush();
            $msg = $semanaEstadistica;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'La Semana Estadítica ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar  la Semana Estadítica';
            }
        }

        return $msg;
    }

    public function modificarSemanaEstadistica($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $semanaEstadistica= $em->getRepository('AppBundle:SemanaEstadistica')->find($data['idSemanaEstadistica']);
            $semanaEstadistica->setFechaInicio(new \DateTime($data['fechaInicio']));
            $semanaEstadistica->setFechaFinal(new \DateTime($data['fechaFinal']));

            $em->persist($semanaEstadistica);
            $em->flush();
            $msg = $semanaEstadistica;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar  la Semana Estadítica';
        }

        return $msg;
    }

    public function eliminarSemanaEstadistica($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $semanaEstadistica = $em->getRepository('AppBundle:SemanaEstadistica')->find($id);

            $em->remove($semanaEstadistica);
            $em->flush();
            $msg = $semanaEstadistica;

        }catch (\Exception $e){

            if(strpos($e->getMessage() , 'foreign key') > 0)
            {
                $msg = 'Existen datos asociados a esta Semana Estadística , no se puede eliminar';
            }
            else
            {
                $msg = 'Se produjo un error al eliminar la Semana Estadística ';
            }
        }
        return $msg;
    }
}
