<?php

namespace AppBundle\Repository;

use AppBundle\Entity\TipoHospital;

/**
 * TipoHospitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoHospitalRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarTipoHospital($data)
    {
        try{
            $em = $this->getEntityManager();
            $tipoHospital = new TipoHospital();
            $tipoHospital->setNombre($data['nombre']);
            $tipoHospital->setCodigo($data['codigo']);

            $em->persist($tipoHospital);
            $em->flush();
            $msg = $tipoHospital;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El tipo de hospital ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el hospital';
            }
        }

        return $msg;
    }

    public function modificarTipoHospital($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $tipoHospital = $em->getRepository('AppBundle:TipoHospital')->find($data['idTipoHospital']);
            $tipoHospital->setNombre($data['nombre']);

            $em->persist($tipoHospital);
            $em->flush();
            $msg = $tipoHospital;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el hospital';
        }

        return $msg;
    }

    public function eliminarTipoHospital($id)
    {
        try {
            $em = $this->getEntityManager();
            $tipoHospital = $em->getRepository('AppBundle:TipoHospital')->find($id);

            $em->remove($tipoHospital);
            $em->flush();
            $msg = $tipoHospital;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen hospitales asociados a esta tipo, no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el hospital';
            }
        }
        return $msg;
    }

}
