<?php

namespace AppBundle\Repository;

/**
 * TipoAreaSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAreaSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
