<?php

namespace AppBundle\Repository;
use Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder;
use AppBundle\Entity\Usuario;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function cambiarPassword($username , $passNew)
    {
        try
        {
            $em = $this->getEntityManager();
            $user = $em->getRepository('AppBundle:Usuario')->findOneBy(array('username' => $username));
            $encoder = new BCryptPasswordEncoder(12);
            $passNew = $encoder->encodePassword($passNew , null);
            $user->setPassword($passNew);

            $em->persist($user);
            $em->flush();
            $msg = $user;

        }catch (\Exception $e){

            $msg = 'Se produjo un error al cambiar la contraseña';

        }
        return $msg;

    }

    public function listarUsuarios($user)
    {
        $em = $this->getEntityManager();
        $nivelAccesoID = $user->getNivelAcceso()->getId();
        $nivelAcceso = $user->getNivelAcceso()->getNivel();

        if($nivelAcceso == 'nacional')
        {
            $dql = 'SELECT u FROM AppBundle:Usuario u WHERE u.isActive = TRUE ';
            $query = $em->createQuery($dql);
        }
        elseif($nivelAcceso == 'provincial')
        {
            if(!empty($user->getAreaSalud()))
            {
                $provincia = $user->getAreaSalud()->getMunicipio()->getProvincia()->getCodigo();
            }else{
                $provincia = $user->getHospital()->getMunicipio()->getProvincia()->getCodigo();
            }
            $dql = 'SELECT u FROM AppBundle:Usuario u JOIN u.nivelAcceso n 
                    LEFT JOIN u.areaSalud a LEFT JOIN a.municipio am LEFT JOIN am.provincia ap
                    LEFT JOIN u.hospital h LEFT JOIN h.municipio hm LEFT JOIN hm.provincia hp
                    WHERE n.id <= :nivel AND (ap.codigo = :codigo OR hp.codigo = :codigo) AND u.isActive = TRUE ';
            $query = $em->createQuery($dql);
            $query->setParameter('nivel' , $nivelAccesoID);
            $query->setParameter('codigo' , $provincia);
        }
        elseif($nivelAcceso == 'municipal')
        {
            if(!empty($user->getAreaSalud()))
            {
                $municipio = $user->getAreaSalud()->getMunicipio()->getCodigo();
            }else{
                $municipio = $user->getHospital()->getMunicipio()->getCodigo();
            }
            $dql = 'SELECT u FROM AppBundle:Usuario u JOIN u.nivelAcceso n 
                    LEFT JOIN u.areaSalud a LEFT JOIN a.municipio am
                    LEFT JOIN u.hospital h LEFT JOIN h.municipio hm
                    WHERE n.id <= :nivel AND (am.codigo = :codigo OR hm.codigo = :codigo) AND u.isActive = TRUE ';
            $query = $em->createQuery($dql);
            $query->setParameter('nivel' , $nivelAccesoID);
            $query->setParameter('codigo' , $municipio);
        }
        else
        {
            if(!empty($user->getAreaSalud()))
            {
                $areaSalud = $user->getAreaSalud()->getCodigo();
            }else{
                $areaSalud = $user->getHospital()->getCodigo();
            }
            $dql = 'SELECT u FROM AppBundle:Usuario u JOIN u.nivelAcceso n
                    LEFT JOIN u.areaSalud a  LEFT JOIN u.hospital h 
                    WHERE n.id = :nivel AND (a.codigo = :codigo OR h.codigo = :codigo) AND u.isActive = TRUE ';
            $query = $em->createQuery($dql);
            $query->setParameter('nivel' , $nivelAccesoID);
            $query->setParameter('codigo' , $areaSalud);
        }
        $usuarios = $query->getResult();

        return $usuarios;
    }

    public function agregarUsuario($data)
    {
        try{
            $em = $this->getEntityManager();
            $user = new Usuario();
            $user->setUsername($data['username']);
            $user->setNombre($data['nombre']);
            $user->setPrimerApellido($data['primerApellido']);
            $user->setSegundoApellido($data['segundoApellido']);

            $nivelAcceso = $em->getRepository('AppBundle:NivelAcceso')->find($data['nivelAcceso']);
            $user->setNivelAcceso($nivelAcceso);

            if($data['areaSalud'] != '0')
            {
                $areaSalud = $em->getRepository('AppBundle:AreaSalud')->find($data['areaSalud']);
                $user->setAreaSalud($areaSalud);
            }else{
                $hospital = $em->getRepository('AppBundle:Hospital')->find($data['hospital']);
                $user->setHospital($hospital);
            }

            $encoder = new BCryptPasswordEncoder(12);
            $encoded = $encoder->encodePassword($data['username'],null);
            $user->setPassword($encoded);

            $usuarioRoles = new ArrayCollection();

            foreach( $data['roles'] as $role)
            {
                $usuarioRoles[] = $em->getRepository('AppBundle:Role')->find($role);
            }
            $user->setUsuarioRoles($usuarioRoles);

            $em->persist($user);
            $em->flush();
            $msg = $user;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El Usuario ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el Usuario';
            }
        }
        return $msg;
    }

    public function eliminarUsuario($id)
    {
        try
        {
            $em = $this->getEntityManager();
            $user = $em->getRepository('AppBundle:Usuario')->find($id);
            $user->setIsActive(0);

            $em->persist($user);
            $em->flush();
            $msg = $user;

        }catch (\Exception $e){

            $msg = 'Se produjo un error al eliminar el Usuario';

        }
        return $msg;
    }

    public function modificarUsuario($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $user = $em->getRepository('AppBundle:Usuario')->findOneBy(array('username' => $data['username']));

            $user->setNombre($data['nombre']);
            $user->setPrimerApellido($data['primerApellido']);

            $user->setSegundoApellido($data['segundoApellido']);

            $nivelAcceso = $em->getRepository('AppBundle:NivelAcceso')->find($data['nivelAcceso']);
            $user->setNivelAcceso($nivelAcceso);

            if($data['areaSalud'] != '0')
            {
                $areaSalud = $em->getRepository('AppBundle:AreaSalud')->find($data['areaSalud']);
                $user->setAreaSalud($areaSalud);
                $user->setHospital(null);
            }else{
                $hospital = $em->getRepository('AppBundle:Hospital')->find($data['hospital']);
                $user->setHospital($hospital);
                $user->setAreaSalud(null);
            }

            $usuarioRoles = new ArrayCollection();

            foreach( $data['roles'] as $role)
            {
                $usuarioRoles[] = $em->getRepository('AppBundle:Role')->findOneBy(array('nombre' => $role));
            }
            $user->setUsuarioRoles($usuarioRoles);

            $em->persist($user);
            $em->flush();
            $msg = $user;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el Usuario';
        }

        return $msg;
    }

}
