<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Xpert;

/**
 * XpertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XpertRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarXpert($data)
    {
        try{
            $em = $this->getEntityManager();
            $xpert = new Xpert();
            $xpert->setClasificacion($data['clasificacion']);
            $xpert->setDescripcion($data['descripcion']);

            $em->persist($xpert);
            $em->flush();
            $msg = $xpert;

        }catch (\Exception $e)
        {
            if(strpos($e->getMessage() , 'Duplicate entry') > 0)
            {
                $msg = 'El Xpert ya existe , no se puede agregar';
            }
            else
            {
                $msg = 'Se produjo un error al insertar el Xpert';
            }
        }

        return $msg;
    }

    public function modificarXpert($data)
    {
        try
        {
            $em = $this->getEntityManager();
            $xpert = $em->getRepository('AppBundle:Xpert')->find($data['idXpert']);
            $xpert->setDescripcion($data['descripcion']);

            $em->persist($xpert);
            $em->flush();
            $msg = $xpert;

        }catch (\Exception $e)
        {
            $msg = 'Se produjo un error al modificar el Xpert';
        }

        return $msg;
    }

    public function eliminarXpert($id)
    {
        try {
            $em = $this->getEntityManager();
            $xpert = $em->getRepository('AppBundle:Xpert')->find($id);

            $em->remove($xpert);
            $em->flush();
            $msg = $xpert;

        } catch (\Exception $e) {

            if (strpos($e->getMessage(), 'foreign key') > 0) {
                $msg = 'Existen pacientes con resultados asociados a este Xpert , no se puede eliminar';
            } else {
                $msg = 'Se produjo un error al eliminar el Xpert';
            }
        }
        return $msg;
    }
}
